name: arnhss
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  provider: ^6.0.3
  dio: ^4.0.6
  flutter_otp_text_field: ^1.1.0
  flutter_keyboard_visibility: ^5.3.0
  lottie: ^1.4.1
  dotted_border: ^2.0.0+2
  http: ^0.13.5
  get: ^4.6.5
  otp_text_field: ^1.1.3
  google_fonts: ^3.0.1
  remixicon: ^1.0.0
  flashy_tab_bar2: ^0.0.4
  rounded_tabbar_widget: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pngs/
    - assets/data/
    - assets/lottie/
    - assets/images/icons/

